name: onefile-tests
on: [push]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'   

      - name: Checking out repo
        uses: actions/checkout@v4

      - name: Installing requirements
        run: |
          python -m venv .venv
          pip install -r requirements.txt

      - name: Running tests 
        run: |
          cd tests
          pytest -v 
