name: onefile-tests
on: [push]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4

      - name: Installing requirements
        run: pip install -r requirements.txt

      - name: Running tests for backend/config.py
        run: |
          cd tests
          pytest -v config_test.py

      - name: Running tests for backend/database_tables.py
        run: pytest -v database_table_test.py

      - name: Running tests for backend/database_utils.py
        run: pytest -v database_utils_test.py
  
